image: Ubuntu2204  # образ для сборки

stack: node 22.11.0  # окружение

branches:
  only:
    - main  # ветка git

cache: node_modules  # кеширование

install:
  - yarn install  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - yarn run build   # команда сборки

test_script:
  - yarn run lint  # скрипт тестирования